server { 
    listen 80;
    index index.php index.html;
    root /var/www/html/public;
    server_name localhosst;

    location / {
        try_files $uri $uri/ /index /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        try_files $uri =404;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
 }